package com.pasha.findactor.model;

import com.pasha.findactor.model.constants.Sequences;
import com.pasha.findactor.model.constants.Tables;
import com.pasha.findactor.model.constants.UserProfileFields;
import com.pasha.findactor.model.constants.UserProfileType;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import javax.persistence.*;
import java.io.Serializable;

/**
 * This class represents {@link Tables#USER_PROFILE} table in database and contains
 * all possible profiles described in {@link UserProfileType} enum.
 *
 * @author Pavel.Krizskiy
 * @see UserProfileType
 * @since 1.0.0
 */
@EqualsAndHashCode
@ToString
@Getter
@Setter
@Entity
@Table(name = Tables.USER_PROFILE)
public final class UserProfile implements Serializable {

    private static final int TYPE_LENGTH = 15;
    private static final String GENERATOR_NAME = "profile_seq";
    private static final int ALLOCATION_SIZE = 1;

    /**
     * Unique id of the profile, generated by sequence in database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = GENERATOR_NAME)
    @SequenceGenerator(name = GENERATOR_NAME,
            sequenceName = Sequences.USER_PROFILE_SEQ, allocationSize = ALLOCATION_SIZE)
    private Integer id;

    @Column(name = UserProfileFields.TYPE, length = TYPE_LENGTH, unique = true, nullable = false)
    private String type = UserProfileType.USER.getUserProfileType();
}
