package com.pasha.findactor.model;

import com.pasha.findactor.model.constants.Sequences;
import com.pasha.findactor.model.constants.Tables;
import com.pasha.findactor.model.constants.WorksheetFields;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import java.util.Date;

/**
 * This class represents a worksheet of candidate for the role.
 * A worksheet contains information about candidate such as candidate's name,
 * nationality, experience, etc.
 * <p>
 * This class is mapped to {@link Tables#WORKSHEET} table in database.
 *
 * @author Pavel Krizskiy
 */
@EqualsAndHashCode
@Getter
@Setter
@Entity
@Table(name = Tables.WORKSHEET)
public class Worksheet {

    private static final String GENERATOR_NAME = "worksheet_seq";
    private static final int ALLOCATION_SIZE = 1;

    /**
     * Unique id of the user, generated by sequence in database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = GENERATOR_NAME)
    @SequenceGenerator(name = GENERATOR_NAME, sequenceName = Sequences.WORKSHEET_SEQ, allocationSize = ALLOCATION_SIZE)
    private Integer id;

    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = WorksheetFields.USER_ID)
    private User user;

    @Column(name = WorksheetFields.SUBMISSIONDATE)
    private Date submissionDate;

    @Column(name = WorksheetFields.AGE)
    private Short age;

    @Column(name = WorksheetFields.HEIGHT)
    private Float height;

    @Column(name = WorksheetFields.WEIGHT)
    private Float weight;

    @Column(name = WorksheetFields.SEX)
    private String sex;

    @Column(name = WorksheetFields.NATIONALITY)
    private String nationality;

    @Column(name = WorksheetFields.EYE_COLOR)
    private String eyeColor;

    @Column(name = WorksheetFields.SKIN_COLOR)
    private String skinColor;

    @Column(name = WorksheetFields.HAIR_COLOR)
    private String hairColor;

    @Column(name = WorksheetFields.EXPERIENCE)
    private String experience;

    /**
     * Why user must get the role.
     */
    @Column(name = WorksheetFields.REASON)
    private String reason;

    @Column(name = WorksheetFields.STATUS)
    private String status;
}